name: rpython-lib

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/*.yml'
      - 'src/**/*.rs'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install maturin
      run: pip3 install maturin
    - name: Build
      run: maturin build --verbose

